export const FILTER_FLYERS = 'FLYERS/FILTER_FLYERS';
export const SEARCH_FLYERS = 'FLYERS/SEARCH_FLYERS';
export const GET_SEARCH_RESULT = 'FLYERS/GET_SEARCH_RESULT';
export const REMOVE_FILTER = 'FLYERS/REMOVE_FILTER';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
