export const FILTER_FLYERS = 'FLYERS/FILTER_FLYERS';
export const SEARCH_FLYERS = 'FLYERS/SEARCH_FLYERS';
export const GET_SEARCH_RESULT = 'FLYERS/GET_SEARCH_RESULT';
export const REMOVE_FILTER = 'FLYERS/REMOVE_FILTER';

export const OPEN_FILTER = 'FILTERS/OPEN_FILTER';
export const SELECT_FILTERS = 'FILTERS/SELECT_FILTERS';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ERROR = 'APP/SHOW_ERROR';
export const SHOW_EMPTY_STATE = 'APP/SHOW_EMPTY_STATE';
